[package]
name = "scraper-rs"
version = "0.2.32"
edition = "2024"

[lib]
name = "scraper_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module", "abi3-py310"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["rt", "macros"] }

scraper = { git = "https://github.com/rust-scraper/scraper", features = ["atomic"] }

xee-xpath = "0.1.5"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
