[package]
name = "scraper-rs"
version = "0.3.2"
edition = "2024"

[lib]
name = "scraper_rs"
crate-type = ["cdylib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.28.2", features = ["abi3-py310"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["rt", "macros"] }

scraper = { version = "0.25.0", git = "https://github.com/rust-scraper/scraper", features = ["atomic"], rev = "f3132d9e06e652e2a4b3031bf7fc3ec3c6a817ce" }

xee-xpath = "0.1.5"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
