from __future__ import annotations

from typing import TypedDict

class ElementDict(TypedDict):
    tag: str
    text: str
    html: str
    attrs: dict[str, str]

class Element:
    tag: str
    text: str
    html: str
    attrs: dict[str, str]

    def __repr__(self) -> str: ...
    def attr(self, name: str) -> str | None: ...
    def get(self, name: str, default: str | None = ...) -> str | None: ...
    def select(self, css: str) -> list[Element]: ...
    def find(self, css: str) -> Element | None: ...
    def css(self, css: str) -> list[Element]: ...
    def to_dict(self) -> ElementDict: ...

class Document:
    html: str
    text: str

    def __init__(self, html: str) -> None: ...
    @classmethod
    def from_html(cls, html: str) -> Document: ...
    def select(self, css: str) -> list[Element]: ...
    def find(self, css: str) -> Element | None: ...
    def css(self, css: str) -> list[Element]: ...
    def __repr__(self) -> str: ...

def parse(html: str) -> Document: ...
def select(html: str, css: str) -> list[Element]: ...
def first(html: str, css: str) -> Element | None: ...
